-- CREATE DATABASE customer_behavior;

select * from customer;
-- Q1.what is the total revenue generated by male vs female customers;
select gender , sum(purchaseamount) as revenue 
from customer 
group by gender;

-- Q2.which customers used a discount but still spent more than average purchase amount
select customerid , purchaseamount
 from customer
 where discountapplied = "yes" and purchaseamount >= ( select avg(purchaseamount) from customer);
 
 -- Q3. which are the top 5 porducts with highest avg review rating
 select itempurchased , round(avg(reviewrating),2) as "average product rating " 
 from  customer 
 group by itempurchased 
 order by avg(reviewrating) desc limit 5;
 
-- Q4.compare the avg purchase amounts between 	standard and express shipping  
select shippingtype, round(avg(purchaseamount),2) 
from customer 
group by shippingtype 
having shippingtype="Express" or shippingtype= "Standard";

select shippingtype, round(avg(purchaseamount),2) 
from customer 
where shippingtype in ("Express","Standard") 
group by shippingtype;

-- Q5 do subscribed customers spend more? compare avg spend and total revenue between subscribers and non subscribers
select subscriptionstatus ,
count(customerid) as total_customers, 
round(avg(purchaseamount),2) as avg_spent , 
round(sum(purchaseamount),2) as total_revenue 
from customer 
group by subscriptionstatus;

-- Q6 which 5 porducts have highest percentage of purchases with discount applied?
select itempurchased, 
round(100 * sum(case when discountapplied = "Yes" then 1 else 0 end) /count(*) ,2) as discount_rate 
from customer 
group by itempurchased 
order by discount_rate desc
limit 5 ;

-- Q7 segment customers into new , returning and loyal based on their total 
-- number of previous purchases and show the count of each segment 	
with customer_type as (
select customerid , previouspurchases ,
case when previouspurchases =1 then 'new'
	when previouspurchases between 2 and 10 then 'returning'
    else 'loyal'
	end as customer_segment
from customer
)
select customer_segment , count(*) as no_of_customers 
from customer_type
group by customer_segment;

-- Q8 what are the top 3 most purchased products from each category 
with item_counts as (
select category , 
itempurchased , 
count(customerid) as total_orders,
row_number() over( partition by category order by count(customerid) desc) as item_rank 
from customer 
group by category , itempurchased
)
select item_rank , category , itempurchased ,total_orders 
from item_counts 
where item_rank<3;

-- Q9 are customers who are repeat buyers ( more than 5 prevous purchases ) also likely to subscribe?
SELECT subscriptionstatus,
       COUNT(customerid) AS repeat_buyers
FROM customer
WHERE previouspurchases > 5
GROUP BY subscriptionstatus;

-- Q10 what is revenue contribution of each age group
select age_group , sum(purchaseamount) as total_revenue 
from customer 
group by age_group 
order by total_revenue desc;

